web_research_task:
  description: >
    Search the Internet for information about how to make trending posts in Instagram, Facebook, Threads and X.com.
    Also search how to make good email marketing and email newsletters.
  expected_output: >
    Write a repport on how to make trending posts in Instagram, Facebook, Threads and X.com and 
    how to make good email marketing and email newsletters.

company_info_analys_task:
  description:
    Read and analyze marketing information from the given file and structure it, 
    so that the inportand info, that may be used in making marketing posts is higher up
  expected_output: >
    Structured company information, ready to be used for making trending social media posts

read_and_get_all_posts_task:
  description: >
    Recursively read and aggregate previous posts
  expected_output: >
    Combined posts content

instagram_trending_post_generator_task:
  description: >
    Generate an Instagram post using company info, previus posts(if there are any) and trending strategies
  expected_output: >
    Instagram post text with tags to be added to the post (don't use markdown language)

dall_e_promt_task:
  description: >
    Generate  an image that will best suit the post
  expected_output: >
    only Instagram image link and nothing else

facebook_trending_post_generator_task:
  description: >
    Generate an facebook post using company info, previus posts(if there are any) and trending strategies
  expected_output: >
    facebook post text with tags to be added to the post (don't use markdown language)

x_com_trending_post_generator_task:
  description: >
    Generate an X.com post using company info, previus posts(if there are any) and trending strategies
  expected_output: >
    X.com post text with tags to be added to the post (don't use markdown language)

threads_trending_post_generator_task:
  description: >
    Generate an Threads post using company info, previus posts(if there are any) and trending strategies
  expected_output: >
    Threads post text with tags to be added to the post (don't use markdown language)

email_newsletter_generator_task:
  description: >
     Write an email newsletter, using company info, previus posts(if there are any) and newsletter writing strategies (don't use markdown, or HTML, because it can't render it)
  expected_output: >
    Email newsletter (don't use markdown language, or HTML, because i can't render it)

email_marketing_generator_task:
  description: >
     Write a marketing email, using company info, previus posts(if there are any) and newsletter writing strategies (don't use markdown, or HTML, because it can't render it)
  expected_output: >
    Marketing email (don't use markdown language, or HTML, because it can't render it)