
web_research_task:
  description: >
    Search the Internet for information about The company {company_name} 
    and it's competitors keep in mind that it is for a competitor analys. use the examples to see what information needs to be found about the company and it's competitors
  expected_output: >
   Write a Detailed report on the company and it's competitors that has all the needed information, so the writer can write a report, similar to the examples i have given

competitor_report_writer_task:
  description: >
    Write a competitor report about the company: {company_name} with the information given to you from the previus agents and files you recieved.
    also, make the article in a similar fashion to the example articles I gave you
  expected_output: >
    The best competitor report for the comany: {company_name} that follows structure similar to the example  competitor reports I gave you

qa_competitor_report_task:
  description: >
    You will recieve an Competitor Report about the company {company_name}. You will review the Competitor Report and fix things if you find something wrong, or if it isn't
    easy to understand and thorough. The Competitor Report need to be in a similar style like the example articles 
  expected_output: >
    Fixed Competitor Report and everything as it is needed. Only the Competitor Report 
    and no remarks from you about the Competitor Report and don't put the whole Competitor Report in a code spippet

